name: Facebook Poster

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes (UTC). Script handles America/Chicago.
  workflow_dispatch: {}       # Manual run button

jobs:
  post-to-facebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run poster
        env:
          HUI_TIMEZONE: "America/Chicago"
          DRY_RUN: "false"  # set "true" to test without posting

          # ====== TOKENS (add these as GitHub Secrets) ======
          # Example names; add/remove to match your destinations.json
          FB_TOKEN_MAIN_PAGE: ${{ secrets.FB_TOKEN_MAIN_PAGE }}
          FB_TOKEN_ART_PAGE:  ${{ secrets.FB_TOKEN_ART_PAGE }}
          FB_TOKEN_TIMMYPOD_GROUP: ${{ secrets.FB_TOKEN_TIMMYPOD_GROUP }}
        run: |
          python post_to_fb.py

      - name: Commit queue updates (marks posted targets)
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content_queue.json
          git commit -m "Autoposter: update posted flags [skip ci]" || echo "No changes"
          git push
